version: 1.1.{build}
image: Visual Studio 2022
configuration: Debug
before_build:
  - nuget restore
build:
  project: .\CM19Lib.sln
  verbosity: minimal
test:
  assemblies:
    only:
      - CM19Lib.Tests/bin/Debug/CM19Lib.Tests.dll
after_test:
  - ps: .\CM19Lib\nuget_pack.ps1
artifacts:
  - path: '*.nupkg'
    name: CM19Lib nupkg
deploy:
  - provider: GitHub
    auth_token:
      secure: EV/QbdjryLysyefCkxLXLBr4icYTdmOi+6wtgrB2mLfrP0qTQPiwj7w4L2i5fi7q
    draft: false
    prerelease: false    
    on:
      appveyor_repo_tag: true
  - provider: NuGet
    api_key:
      secure: QHC8Twb1rsEXWGXXNzQhuQowwvBUVecFB0iPkPG5Y8I0zCKeBcRk3oWgEhB5zHR8
    skip_symbols: false
    artifact: /.*\.nupkg/
    on:
      appveyor_repo_tag: true

