version: 1.1.{build}
image: Visual Studio 2022
configuration: Debug
before_build:
  - nuget restore
build:
  project: .\CM19Lib.sln
  verbosity: minimal
test:
  assemblies:
    only:
      - CM19Lib.Tests/bin/Debug/CM19Lib.Tests.dll
after_test:
  - ps: .\CM19Lib\nuget_pack.ps1
artifacts:
  - path: '*.nupkg'
    name: CM19Lib nupkg
deploy:
  - provider: GitHub
    auth_token:
      secure: q0rRgZDDKmOASUrMCHGUlPh34wIipSYKWJiDeiwftkB7hLH/QyYhNL5MckCyse+1
    draft: false
    prerelease: false    
    on:
      appveyor_repo_tag: true
  - provider: NuGet
    api_key:
      secure: xe7KBrpDVPQYOr4XpJNPs2/9vdT5lO/qV5z8Qrv3yXWd6kQScl3UfB5WaF7olbfy
    skip_symbols: false
    artifact: /.*\.nupkg/
    on:
      appveyor_repo_tag: true

